Project_Code/webjax/Code/src/courses/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, LessonDetailView

app_name = 'courses'

urlpatterns = [
	path('', CourseListView.as_view(), name='list'),
	path('<slug>', CourseDetailView.as_view(), name='detail'),
	path('<course_slug>/<lesson_slug>', LessonDetailView.as_view(), name='lesson-detail')
	]

Project_Code/webjax/Code/src/memberships/urls.py
from django.urls import path

from .views import (
    MembershipSelectView,
    PaymentView,
    updateTransactionRecords,
    profile_view,
    )

app_name = 'memberships'

urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select'),
    path('payment/', PaymentView, name='payment'),
    path('update-transactions/<subscription_id>/',
         updateTransactionRecords, name='update-transactions'),
    path('profile/', profile_view, name='profile'),
    ]

Project_Code/webjax/Code/src/videoservice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('memberships/', include('memberships.urls', namespace='memberships')),
    path('courses/',include('courses.urls', namespace='courses')),
    #path('accounts/', include('allauth.urls')),
 ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project_Code/webjax/Code/src/courses/models.py
from django.db import models
from django.urls import reverse
from memberships.models import Membership
# Create your models here.

class Course(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=120)
	description = models.TextField()
	allowed_memberships = models.ManyToManyField(Membership)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:detail', kwargs={'slug': self.slug})

	@property
	def lessons(self):
		return self.lesson_set.all().order_by('position')



class Lesson(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=120)
	course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
	position = models.IntegerField()
	video_url = models.CharField(max_length=200)
	thumbnail = models.ImageField()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:lesson-detail',
			kwargs={
			'course_slug': self.course.slug,
			'lesson_slug': self.slug
			})

Project_Code/webjax/Code/src/courses/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView, View

from memberships.models import UserMembership
from .models import Course, Lesson

class CourseListView(ListView):
	model = Course

class CourseDetailView(DetailView):
	model = Course
		
class LessonDetailView(View):

	def get(self, request, course_slug, lesson_slug, *args, **kwargs):

		course_qs = Course.objects.filter(slug=course_slug)
		if course_qs.exists():
			course = course_qs.first()

		lesson_qs = course.lessons.filter(slug=lesson_slug)
		if lesson_qs.exists():
			lesson = lesson_qs.first()


		user_membership = UserMembership.objects.filter(user=request.user).first()
		user_membership_type = user_membership.membership

		course_allowed_mem_types = course.allowed_memberships.all()

		context = { 'object': None }

		if course_allowed_mem_types.filter(membership_type=user_membership_type).exists():
			context = { 'object': lesson}

		return render(request, "courses/lesson_detail.html", context)

Project_Code/webjax/Code/src/courses/templates/courses/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

	{% include 'courses/messages.html' %}

	<div class="container">
		<ol class='breadcrumb'>
	        <li> <a href="/"> Home </a> </li>
	        <li> <a href="/profile"> Profile </a> </li>
	        {% block post_detail_link %}
	        {% endblock %}

	        {% if not request.user.is_authenticated %}
	        <li class='pull-right'><a href='/register'>Register</a></li>
	        <li class='pull-right'><a href='/login'>Login</a></li>
	        {% else %}
	        <li class='pull-right'><a href='/memberships'>Memberships</a></li>
	        {% endif %}
	    </ol>
	</div>

	{% block content %}

	{% endblock content %}

	<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

Project_Code/webjax/Code/src/courses/templates/courses/course_detail.html
{% extends 'courses/base.html' %}

{% block post_detail_link %}
<li>{{ object.title }}</li>
{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-sm-4 col-md-4">
				<h1>Course Detail View Page</h1>
				<h3>{{ object.title }}</h3>
				<p>{{ object.description }}</p>
				<ol>
					{% for lesson in object.lessons %}
					<li><a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}</a></li>
					{% endfor %}
				</ol>
				
			</div>
		</div>
	</div>

{% endblock %}

Project_Code/webjax/Code/src/courses/templates/courses/course_list.html
{% extends 'courses/base.html' %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-sm-4 col-md-4">
				<h1>Course List View Page</h1>
				{% for object in object_list %}
					<a href="{{ object.get_absolute_url }}">{{ object }}</a>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

Project_Code/webjax/Code/src/courses/templates/courses/lesson_detail.html
{% extends 'courses/base.html' %}

{% block post_detail_link %}
{% if object is not None %}
	<li><a href="{{ object.course.get_absolute_url }}">{{ object.course.title }}</a></li>
	<li>{{ object.title }}</li>
{% endif %}
{% endblock %}

{% block content %}
	<div class='container'>
		<h1>Lesson Detail View</h1>
		<div class='row'>
			<div class='col-sm-6 col-md-6'>
				{% if object is not None %}
				<h3>{{ object.title }}</h3>
				<p>{{ object.description }}</p>
				
				<video controls
					   controlsList="nodownload"
					   poster="{{ object.thumbnail.url }}"
				       src="/static{{ object.video_url }}"
				       width="300"
				       height="200">
				    Sorry, your browser doesn't support embedded videos.
				</video>
				{% else %}
				<h3>Upgrade membership</h3>
				<p>To view this course you'll need to upgrade your membership</p>
				<br>
				<a href="{% url 'memberships:select' %}"><button class="btn btn-warning">Check out memberships</button></a>
				<hr>
				{% endif %}
			</div>
		</div>
	</div>

{% endblock content %}

Project_Code/webjax/Code/src/courses/templates/courses/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>
</div>

{% endif %}